# Generated by Django 3.2.12 on 2022-03-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('numero_dosis', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dui', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.IntegerField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vacunacion', models.DateField()),
            ],
            options={
                'db_table': 'registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('nombre_vacuna', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=50)),
                ('pais_fabricacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_vacuna',
                'managed': False,
            },
        ),
    ]
